"use client";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

import AuthGuard from "./components/AuthGuard";
import { useEffect, useState } from "react";

function Navbar() {
  const [loggedIn, setLoggedIn] = useState(false);
  const [account, setAccount] = useState("");

  useEffect(() => {
    if (typeof window !== "undefined") {
      setLoggedIn(window.localStorage.getItem("bank_logged_in") === "true");
      setAccount(window.localStorage.getItem("bank_account") || "");
    }
    const handler = () => {
      setLoggedIn(window.localStorage.getItem("bank_logged_in") === "true");
      setAccount(window.localStorage.getItem("bank_account") || "");
    };
    window.addEventListener("storage", handler);
    return () => window.removeEventListener("storage", handler);
  }, []);

  function logout() {
    if (typeof window !== "undefined") {
      window.localStorage.removeItem("bank_logged_in");
      window.localStorage.removeItem("bank_account");
      window.location.href = "/login";
    }
  }

  return (
    <nav className="glass-card shadow-lg mx-auto mt-6 mb-10 flex flex-wrap gap-6 items-center justify-center px-10 py-4 border border-blue-200/40 backdrop-blur-md" style={{fontFamily: 'var(--font-geist-sans)'}}>
      {!loggedIn && <a className="text-lg font-semibold text-blue-800 hover:text-blue-600 transition-colors" href="/login">Login</a>}
      <a className="text-lg font-semibold text-blue-800 hover:text-blue-600 transition-colors" href="/summary">Account Summary</a>
      <a className="text-lg font-semibold text-blue-800 hover:text-blue-600 transition-colors" href="/transactions">Transactions</a>
      <a className="text-lg font-semibold text-blue-800 hover:text-blue-600 transition-colors" href="/transfer">Transfer Money</a>
      {loggedIn && (
        <>
          <span className="ml-6 font-mono bg-blue-900/80 text-white px-4 py-2 rounded-xl text-base shadow-sm">{account}</span>
          <button onClick={logout} className="ml-4 button-main shadow-md">Logout</button>
        </>
      )}
    </nav>
  );
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Navbar />
        <AuthGuard>{children}</AuthGuard>
      </body>
    </html>
  );
}

