"use client";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

import AuthGuard from "./components/AuthGuard";
import { useEffect, useState } from "react";

function Navbar() {
  const [loggedIn, setLoggedIn] = useState(false);
  const [account, setAccount] = useState("");

  useEffect(() => {
    if (typeof window !== "undefined") {
      setLoggedIn(window.localStorage.getItem("bank_logged_in") === "true");
      setAccount(window.localStorage.getItem("bank_account") || "");
    }
    const handler = () => {
      setLoggedIn(window.localStorage.getItem("bank_logged_in") === "true");
      setAccount(window.localStorage.getItem("bank_account") || "");
    };
    window.addEventListener("storage", handler);
    return () => window.removeEventListener("storage", handler);
  }, []);

  function logout() {
    if (typeof window !== "undefined") {
      window.localStorage.removeItem("bank_logged_in");
      window.localStorage.removeItem("bank_account");
      window.location.href = "/login";
    }
  }

  return (
    <nav className="bg-blue-700 text-white px-6 py-3 flex gap-4 items-center justify-center">
      {!loggedIn && <a className="hover:underline" href="/login">Login</a>}
      <a className="hover:underline" href="/summary">Account Summary</a>
      <a className="hover:underline" href="/transactions">Transactions</a>
      <a className="hover:underline" href="/transfer">Transfer Money</a>
      {loggedIn && (
        <>
          <span className="ml-4 font-mono bg-blue-900 px-2 py-1 rounded">{account}</span>
          <button onClick={logout} className="ml-2 bg-white text-blue-700 px-3 py-1 rounded hover:bg-blue-100">Logout</button>
        </>
      )}
    </nav>
  );
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Navbar />
        <AuthGuard>{children}</AuthGuard>
      </body>
    </html>
  );
}

